### ISSUE TITLE
MRIQC running on CamCAN for 24+ hours

### ISSUE THREAD

**Issue by tsalo** [NBCLab/power-replication#7]
Each subject is currently still running MRIQC, 24 hours after submission. It _should_ only take ~2 hours per subject, so I'm not sure what's going on. The only thing I can think of is that maybe pybids is having trouble with the size of the dataset, since there are 600+ subjects?

**Comment by tsalo** [comment]
Currently trying an approach where each subject's data and the BIDS top-level files are copied to a new mini-dataset before running MRIQC. I will see if this speeds things up. 🤞

**Comment by emdupre** [comment]
:crossed_fingers: Good luck !!
Do the logs reveal if it's stuck on any particular step ? Or is it just slow generally ?

**Comment by tsalo** [comment]
I checked the stderr and stdout but didn't look at the mriqc logs. The single-subject dataset version runs fairly well, so I think it just came from the size of the full dataset.

**Comment by tsalo** [comment]
Things seem to be progressing nicely. 14 failed on one or more runs/images, so I'm re-running them now.

Ultimately, most finished in ~2-2.5 hours.
